title = "Ordinary Differential Equations"
url = "https://sandyuraz.com/math220_sp21"
#url = "/Users/thecsw/gits/sandyuraz"

[website]
locale = "en_GB"
color = "#fffff4"
twitter = "@sandyuraz"
styles = ["https://sandyuraz.com/css/darkness.css"]
tombs = []

[author]
image = "rei.png"
name = "email"
email = "ctu [at] ku [dot] edu"

[navigation]

[navigation.1]
link = ""
title = "Home ğŸ "
